<td>
    <script type="text/javascript">
        require(["jquery", "jquery/ui"], function (jq) {
            jq(document).ready(function () {
                jq("#<?= $block->getHtmlId(); ?>").datepicker( { dateFormat: "yy/mm/dd" } );
                jq(".ui-datepicker-trigger").removeAttr("style");
                jq(".ui-datepicker-trigger").click(function(){
                    jq("#<?= $block->getHtmlId(); ?>").focus();
                });
            });
        });
    </script>
</td>